""" REMOTE MESSAGE TYPES """
POLLING_TYPE_NAME = "polling"
EXECREPLY_TYPE_NAME = "execreply"

""" LOCAL MESSAGE TYPES """
POLLING_TYPE_CODE = 0
EXEC_TYPE_CODE = 1

""" POLLING MESSAGE RESPONSE TYPES """
POLLING_REPONSE_NOP = 0
POLLING_REPONSE_EXIT = 1

""" EXECUTION ERROR VALUES """

ERROR_VALUES = [
    "ERROR_INVALID_CONTEXT",
    "ERROR_WIRE_HANDLER",
    "ERROR_GRID_HANDLER",
    "ERROR_AREA_HANDLER",
    "ERROR_ARC_HANDLER",
    "ERROR_ATTRIBUTE_HANDLER",
    "ERROR_CIRCLE_HANDLER",
    "ERROR_CLASS_HANDLER",
    "ERROR_DIMENSION_HANDLER",
    "ERROR_ELEMENT_HANDLER",
    "ERROR_PACKAGE_HANDLER",
    "ERROR_TEXT_HANDLER",
    "ERROR_CONTACT_HANDLER",
    "ERROR_POLYGON_HANDLER",
    "ERROR_FRAME_HANDLER",
    "ERROR_RECTANGLE_HANDLER",
    "ERROR_HOLE_HANDLER",
    "ERROR_LAYER_HANDLER",
    "ERROR_LIBRARY_HANDLER",
    "ERROR_DEVICE_HANDLER",
    "ERROR_DEVICESET_HANDLER",
    "ERROR_SYMBOL_HANDLER",
    "ERROR_GATE_HANDLER",
    "ERROR_PIN_HANDLER",
    "ERROR_PAD_HANDLER",
    "ERROR_PINREF_HANDLER",
    "ERROR_SIGNAL_HANDLER",
    "ERROR_VIA_HANDLER",
    "ERROR_VARIANTDEF_HANDLER",
    "ERROR_VARIANT_HANDLER",
    "ERROR_PART_HANDLER",
    "ERROR_INSTANCE_HANDLER",
    "ERROR_JUNCTION_HANDLER",
    "ERROR_SEGMENT_HANDLER",
    "ERROR_LABEL_HANDLER",
    "ERROR_NET_HANDLER",
    "ERROR_BUS_HANDLER",
    "ERROR_CONTACTREF_HANDLER",
    "ERROR_BOARD_HANDLER",
    "ERROR_SCHEMATIC_HANDLER",
    "ERROR_SHEET_HANDLER",
    "ERROR_MAX_DEPTH",
    "ERROR_BASE_HANDLER"]

""" CONTEXT """


class CONTEXT:
    BOARD = 0
    SCHEMATIC = 1
    SHEET = 2
    PACKAGE = 3
    LIBRARY = 4

""" EAGLE COMMANDS """


class COMMAND:
    dlgMessageBox = 100
    ingroup = 101
    clrgroupall = 102
    allobjects = 103
    setgroup = 104
    executescr = 105
    getcontext = 106
    getattribute = 107
    setattribute = 108
    palette = 109
    paletteall = 110
    getselected = 111
    status = 112


class PALETTE:
    DEFAULT = -1
    BLACK = 0
    WHITE = 1
    COLORED = 2
    TYPES = 3
    ENTRIES = 64


class GRID:
    class UNIT:        
        MIC = 0
        MM = 1
        MIL = 2
        INCH = 3
        
    class VALUE:
        LAST = -1
        FINEST = -2
        DEFAULT = -3

REFRESH_VALUE = False
CACHED_VALUE = True